### ISSUE TITLE
About original data

### ISSUE THREAD

**Issue by lly-louis** [yunhao-zou/RawHDR#5]
Hi, what a valuable work!

However, I find the released dataset only including the input images (0 EV) and the HDR images. Would you mind releasing the original RAW files on different exposures? I think that would be much useful!

By the way, may I ask which implementation of `Recovering High Dynamic Range Radiance Maps from Photographs (Debevec etal., 2008)` did you use? And how did you filter the misaligned pairs? (Sorry for such trivial questions, but I suppose maybe we can help enlarge this dataset on different cameras!)

Thanks!

**Comment by yunhao-zou** [comment]
Hi, is it convenient for you to use Baidudisk? If so, I can upload the original RAW files in Baidudisk. We use this [**code**](https://github.com/fthaler/rawhdr) to fuse multiple RAW images to HDR. As for excluding misaligned pairs, since we carefully fix the camera on a steady tripod, we find that the camera motion is almost unrecognizable, so we mainly filter those pairs with object motion :)

**Comment by lly-louis** [comment]
Yes, Baidudisk is OK for me! Thanks for sharing these information！

**Comment by yunhao-zou** [comment]
> Yes, Baidudisk is OK for me! Thanks for sharing these information！

The RAW files are uploaded to [**[BaiduDisk]**](https://pan.baidu.com/s/1HOxGhTEY9whGxbEEw1QAjw)(4fxm), you can use it at your convience. Please note that every three images (sorted by filename) make up for bracket exposures for one scene
